react init
EasyBrizy/builder pull request #33
Opened 2023-07-25 09:12 UTC by Nessunskill

reactjs example

2023-08-01 07:24 UTC, maxval1 requested changes

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/package.json
> +  "name": "reactjs",
rename to `@brizy/reactjs`

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/package.json
> +    "@types/react-dom": "^18.2.6",
normalize all `dependencies` some of the is part of `devDependencies`

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/package.json
> +    ]
same `browserslist` for all env

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/public/logo192.png
is used?

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/public/logo512.png
is used?

2023-08-01 07:24 UTC, maxval1 commented on examples/reactjs/src/pages/page.tsx
> +    console.log("Found page in cache");
1. remove `console.log`
2. remove cache

2023-08-01 07:24 UTC, maxval1 commented on packages/sdk/src/client/resource.ts
> +      ? "demo server"
change `demo server` to beta1

2023-08-01 07:24 UTC, maxval1 commented on packages/react/src/Scripts/index.tsx
> +    `document.addEventListener('DOMContentLoaded', () => window.Brz.emit("init.dom", jQuery(document.body)))`
this is main script

2023-08-01 07:24 UTC, maxval1 commented on packages/react/src/Scripts/index.tsx
> +      }
need to execute all of this only if is in browser and not SSR

2023-08-01 07:25 UTC, maxval1 requested changes

2023-08-01 07:25 UTC, maxval1 commented on packages/react/src/Scripts/index.tsx
> +      if (script.html && !isBrizyInitScript(script)) {
why it's neede?

2023-08-01 07:37 UTC, Nessunskill commented on packages/react/src/Scripts/index.tsx
> +      if (script.html && !isBrizyInitScript(script)) {
If inline script received and it's not brizy main script we should load it. Only main script should be skipped

2023-08-01 10:06 UTC, maxval1 requested changes

2023-08-01 10:06 UTC, maxval1 commented on packages/react/src/types.ts
> +}
omit all of them

2023-08-03 04:46 UTC, maxval1 requested changes
Need to add `npm run build:reactjs` in package.json inside root to build only react example same like npm run build:nextjs

2023-08-03 04:46 UTC, maxval1 commented on packages/react/src/hooks/useLoadScript.ts
> +          // @ts-ignore
change `@ts-ignore` to `ts-expect-error: My Message`

2023-08-03 10:22 UTC, merged