Placeholders init project
EasyBrizy/builder pull request #44
Opened 2023-08-30 16:24 UTC by GunkaArtur

2023-09-25 08:39 UTC, lift46252 requested changes

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +  buildPlaceholder(): string {
add empty line

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +        return `{{${_placeholder}${attrs}}}`
in original if attrs have length is added a empty space https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/AbstractPlaceholder.php#L39 are you sure you not need this in your case ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +      return `{{${_placeholder}}`
refactor here to `{{${_placeholder}${attrs}}}` amd remove it from line 52 because if attrs is empty this will return the same paleholder as now on line 55 if attrs is not empty will be returned placeholders with him

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +}
i not see this methods https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/AbstractPlaceholder.php#L81 in you js implimentation are you sure that you not need it ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +        Math.random().toString(36).substring(2, 15),
maybe need to extract this in a utils as i see you use it multiple times ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +    return content
as i see on all set fns in original https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/ContentPlaceholder.php#L186 is returned `this` are you sure that here you need to return only changed value (actual for all setFns)

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +      placeholder = placeholder + content + `{{end_${name}}}`
you can use += here to be shorten,and as i know is better to use `${}` syntax

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +    let placeholder = "{{" + name + " " + attrs + "}}"
same here

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +}
some methods is common for multiple class maybe you can create a parent class for this cases and extend it ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +    /(?<placeholder>{{\s*(?<placeholderName>.+?)\s*(?<attributes>\s+((?:\w+(?:\[(?:\w+)?\])?\s*=\s*(?:'|\"|\&quot;|\&apos;|\&#x27;)(?:.*?)(?<!\\\\)(?:'|\"|\&quot;|\&apos;|\&#x27;)\s*)*))?}}(?:(?<cont
why on your regex is 2 instead g{placeholderName})  https://github.com/bagrinsergiu/brizy-content-placeholder/blob/6454569bd8982a53e1fd56e64fe9ef2b2cc18c73/lib/Extractor.php#L12C246-L12C265

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +    /(?<attr_name>\w+)\s*=\s*(?<quote>'|"|&quot;|&apos;|&#x27;)(?<attr_value>.*?)\2/g
same here https://github.com/bagrinsergiu/brizy-content-placeholder/blob/6454569bd8982a53e1fd56e64fe9ef2b2cc18c73/lib/Extractor.php#L14C49-L14C82

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +        match[0],
why [0] ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +
where is this fn https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/Extractor.php#L89

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +      if (isArray && attrName && attrValue) {
remove && attrname you already know it exist because if not you will not be on this line of code

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +        }
gere is the same code so maybe you can write this on lines after if ?

2023-09-25 08:39 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/PlaceholderInterface.ts
> +export interface PlaceholderInterface {
where is this https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/PlaceholderInterface.php#L7C5-L7C37

2023-10-09 11:39 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +}
Yes, I'm sure

2023-10-09 11:42 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +    /(?<placeholder>{{\s*(?<placeholderName>.+?)\s*(?<attributes>\s+((?:\w+(?:\[(?:\w+)?\])?\s*=\s*(?:'|\"|\&quot;|\&apos;|\&#x27;)(?:.*?)(?<!\\\\)(?:'|\"|\&quot;|\&apos;|\&#x27;)\s*)*))?}}(?:(?<cont
Regex in PHP and in JS have some differences, copy/paste from PHP will not work correctly

2023-10-09 11:42 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +    /(?<attr_name>\w+)\s*=\s*(?<quote>'|"|&quot;|&apos;|&#x27;)(?<attr_value>.*?)\2/g
same here

2023-10-09 11:42 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +
No need here

2023-10-09 11:45 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/PlaceholderInterface.ts
> +export interface PlaceholderInterface {
https://github.com/EasyBrizy/builder/blob/3d344e6797eed7ff52f5a49f52b96aa5d93d7c3b/packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts#L7

here

2023-10-09 11:54 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/Extractor.ts
> +        match[0],
I need first match group here

2023-10-09 12:05 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +    return content
in PHP there is realized this pattern https://ru.wikipedia.org/wiki/Fluent_interface that is not mandatory

2023-10-09 13:08 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +}
The original project don't have this and `ContentPlaceholder` has some common values with `AbstractPlaceholder` and `AbstractPlaceholder` already implements `PlaceholderInterface` and I think it's not needed to create one more interface, let's keep this classes separately with their own properties

2023-10-11 08:30 UTC, lift46252 requested changes

2023-10-11 08:30 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/AbstractPlaceholder.ts
> +      return `{{${_placeholder} ${attrs}}}`
if attrs will be empty space will remain but in original space exist only if attrs is not empty
https://github.com/bagrinsergiu/brizy-content-placeholder/blob/master/lib/AbstractPlaceholder.php#L39

2023-10-11 08:30 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/utils.ts
> +export const createUid = ():string => Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15)
and pretify please

2023-10-11 08:30 UTC, lift46252 commented on packages/brizy-content-placeholder/src/tests/contentPlaceholder.test.ts
> +    expect(contentPlaceholder.getUid()).toBeDefined()
if you get UId it shouldn't return uid ? how on getId ? and how here https://github.com/EasyBrizy/builder/pull/44/files#diff-46249bceb58f49d1876140c3301006ed65bbe1e7d645b7550be6d26b50678f56R45

2023-10-11 08:30 UTC, lift46252 commented on packages/brizy-content-placeholder/src/tests/registry.test.ts
> +    getVaryAttributes: jest.fn(),
you repeat multiple times all this values you can create a common const for him and if will needed reset mock before each test

2023-10-11 08:30 UTC, lift46252 commented on packages/brizy-content-placeholder/src/modules/ContentPlaceholder.ts
> +    let placeholder = `{{${name} ${attrs}}}`
same here

2023-10-11 13:42 UTC, GunkaArtur commented on packages/brizy-content-placeholder/src/tests/contentPlaceholder.test.ts
> +    expect(contentPlaceholder.getUid()).toBeDefined()
UID is created random I don't know the exact ID how in ID

2023-10-11 13:44 UTC, GunkaArtur commented on packages/brizy-content-placeholder/package.json
> +    "typescript": "5.1.6"
I don't see any problem here, if problems will appear, we can downgrade, until there let's keep actual version

2023-10-11 15:20 UTC, lift46252 requested changes

2023-10-13 06:16 UTC, lift46252 approved these changes

2023-10-17 12:30 UTC, lift46252 approved these changes

2023-10-17 12:37 UTC, merged