Mock CMS plugin
EasyBrizy/builder pull request #53
Opened 2023-10-19 08:08 UTC by Nessunskill

2023-10-20 06:47 UTC, lift46252 requested changes

2023-10-20 06:47 UTC, lift46252 commented on core/src/abstractPlugin/AbstractPlugin.ts
> +    // console.log(`handleAction: ${this.name}, ${JSON.stringify(action)}`);
remove comment

2023-10-20 06:47 UTC, lift46252 commented on core/src/core/index.ts
> +      }
try to avoid type assertion here add and is fn for collectionType and check on him in if

2023-10-20 06:47 UTC, lift46252 commented on core/src/core/index.ts
> +    });
same here

2023-10-20 06:47 UTC, lift46252 commented on core/src/core/index.ts
> +    this.addHook(FilterTypes.BUILDER_EDIT_LINK, (collection: any) => {
try to remove any

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    console.log(collTypes);
remove console.log

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    return [
make it niline

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    return [
same here

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    return [
same here

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +  // @ts-expect-error: accept implicitly any
maybe you can avoid this ? for example as i see accept is used as value of attribute attreibute values in our case ussualy is strings maybe you can determinate type ?

2023-10-20 06:47 UTC, lift46252 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +        // @ts-expect-error: files maybe null
remove and try `el.files?[0]`

2023-10-20 06:47 UTC, lift46252 commented on core/src/types/type.ts
> +    fields: Array<any>;
same here

2023-10-20 06:47 UTC, lift46252 commented on core/src/types/type.ts
> +    }>;
please create separate interface for every object because is hard to read as is now and you can write `type[]` instead `Array<type>`

2023-10-20 06:47 UTC, lift46252 commented on core/src/types/type.ts
> +    };
same here

2023-10-20 06:47 UTC, lift46252 commented on examples/nextjs/src/components/Brizy/index.tsx
> +      <div id="editor" style={{ height: "100vh" }} ref={containerRef}></div>
{ height: "100vh" } shouold be a separate const

2023-10-20 06:47 UTC, lift46252 commented on examples/nextjs/src/components/Brizy/index.tsx
> +  let isBuilderRendered = false;
maybe ref instead let ?

2023-10-20 06:47 UTC, lift46252 commented on plugins/brizyApiClient/src/index.ts
> +export { BrizyApiClient };
you can export directly in one line as i know

2023-10-27 04:29 UTC, maxval1 requested changes
conflicts

2023-10-30 06:43 UTC, maxval1 requested changes

2023-10-30 06:43 UTC, maxval1 commented on core/src/core/index.ts
> +    this.addHook(HookTypes.BUILDER_EDIT_LINK, (collection: any) => {
remove `any`

2023-10-30 06:43 UTC, maxval1 commented on core/src/core/index.ts
> +      return `${window.location.origin}/admin/?type=${collection.pageData.collectionType.title}&slug=${collection.pageData.slug}`;
????

2023-10-30 06:43 UTC, maxval1 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    this.applyHook("ADD_COLLECTION_TYPE", demoConfig2.pageData.collectionType);
why need 2 configs?

2023-10-30 06:43 UTC, maxval1 commented on core/src/plugins/mockApiClient/mockApiClient.ts
> +    this.addHook("GET_PREVIEW_LINK", () => "/preview");
why need this in api client?

2023-10-30 06:43 UTC, maxval1 commented on core/src/types/type.ts
> +    fields: Array<any>;
remove `any` use concret type

2023-10-30 06:43 UTC, maxval1 commented on core/src/types/type.ts
> +  pageData: {
i think all types about the `pageData` and `projectData` is Record<string, unknown>

2023-10-30 06:43 UTC, maxval1 commented on plugins/builder/src/plugin/builder.ts
> +      //TODO: should pagePreview be defined in mockApiClient?
nope....

2023-10-30 06:43 UTC, maxval1 commented on plugins/builder/src/plugin/builder.ts
> +    this.core.dispatch({ type: "RENDER_CMS" }, "Builder");
why need render_cms here?

2023-10-30 06:43 UTC, maxval1 commented on plugins/cms/src/plugin/cms.ts
> +  renderItems = (items: any[]) => {
`any`

2023-11-03 09:53 UTC, merged